#!/bin/sh
#
# Copyright (C) 2023 parazyd <parazyd@dyne.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# Dependencies: socat, inotify-tools

HOST="${1:-plebaudio-server.lan:2115}"

FIFO="/tmp/plebaudio.sock"
LOCK="/tmp/.plebaudio.lock"

rm -f "$FIFO"
touch "$LOCK"
mkfifo -m 0664 "$FIFO"

# Open a writer to keep the pipe alive
inotifywait "$LOCK" > "$FIFO" &

trap ctrl_c INT
ctrl_c() {
	printf "\r"
	rm -f "$FIFO" "$LOCK"
	echo "Bye"
	exit 0
}

socat -b 2048 -u "$FIFO" "UDP4-SENDTO:${HOST}"
